version: '3.8'

services:
  # AI Service - Emotion Detection Webhook Only
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: carrie-ai
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - carrie-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend Service - API & Auth
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carrie-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AI_SERVICE_URL=http://ai:5000
    depends_on:
      - ai
    networks:
      - carrie-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service - React/Vite UI
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: carrie-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - ai
    networks:
      - carrie-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  carrie-network:
    driver: bridge

volumes:
  huggingface-cache:
    driver: local
